RegenMap=0
cat /dev/null >itemList
cat /dev/null >itemContains
cat /dev/null >HeatingReplacedNormal.zs
cat /dev/null >HeatingReplacedExpert.zs
export copyright="/*
 * Copyright (c) 2023.
 * Original Author: TeamMoeg
 * https://teammoeg.com
 * Unofficial Version Main Author: kuzuanpa
 * https://github.com/kuzuanpa
 *
 * This is A ZenScript generated by bash shell
 * Original file can be founded in ../../../shellScript/heatingItemRewrite/HeatingItem.zs
 *
 * This file is distributed as part of the Terrafirma: Rescue Unofficial Modpack.
 * Visit whole Source Code on Github:
 * https://github.com/kuzuanpa/Modpack-TerraFirma-Rescue-Unofficial
 *
 * Terrafirma: Rescue Unofficial is a fork of Terrafirma: Rescue, Visit their Source Code on Github:
 * https://github.com/TerraFirmaRescue/TerraFirma-Rescue-Modpack
 *
 * Terrafirma: Rescue Unofficial is a Free and Open Source Software distributed under the
 * Terrafirma: Rescue License: https://github.com/TerraFirmaRescue/TerraFirma-Rescue-Modpack/blob/master/LICENSE
 *
 */"
while :; do
  echo "Regen Item containing material list?[1/0]"
  read askregenItemlist
  if [ $askregenItemlist -eq 1 ]; then
    RegenMap=1
    cat /dev/null >containingMap
    break
  elif [ $askregenItemlist -eq 0 ]; then
    find . -name containingMap
    if [ $? -ne 0 ]; then
      echo "Not found ContainingMap! Please regen now"
    else
      break
    fi
  fi
done
echo "$copyright" >> HeatingReplacedNormal.zs
echo "$copyright" >> HeatingReplacedExpert.zs
cat HeatingItems.zs | while read line; do
  echo $line | grep -q ^mods
  if [ $? -eq 0 ]; then
    material=$(echo $line | grep -o -E 'gt.meta.*?\:[0-9]+' | grep -o -E "[0-9]+")
    item=$(echo $line | grep -o -E 'gt.meta.*?\:' | sed 's/gt.meta.//')
    if [ $RegenMap -eq 1 ]; then
      grep -q -w $item itemList
      if [ $? -ne 0 ]; then
        echo -n "$item  " >>itemList
      fi
    else
      containing=$(grep -w $item containingMap | sed "s/$item //")
      echo $line | sed "s/uk/\<gregtech:gt.meta.chunkGt\:$material\>\*$containing/" >> HeatingReplacedNormal.zs
      echo $line | sed "s/uk/\<terrafirmacraft\:item.Unknown\ Ingot\>\*$containing/" >> HeatingReplacedExpert.zs
    fi
  fi
done
if [ $RegenMap -eq 1 ]; then
  echo "You need to input these items Contains. (Chunks num, 4 = One ingot/dust)"
  cat itemList
  echo " "
  echo "(Enter to continue)"
  read
  echo ">>Enter contains:"
  read contains
  echo $contains >itemContains
  for item in $(cat itemList); do
    itemContain=$(grep -o -E "^[0-9]+" itemContains)
    echo "$item $itemContain" >>containingMap
    sed -i s/^[0-9]*\ // itemContains
  done
fi
rm itemContains
rm itemList
